mirror: update gcontacts script to python3

diff --git a/mirror/gcontacts b/mirror/gcontacts
--- a/mirror/gcontacts
+++ b/mirror/gcontacts
@@ -5,22 +5,17 @@
 # file, You can obtain one at http://mozilla.org/MPL/2.0/.
 #
 
-# This script backs up your Google contacts.  To use, run 'gcontacts -u' first
+# This script backs up your Google contacts.  To use, run 'backup' first
 # interactively.
 
 cd $(dirname $0)
-if ! ~/bin/gcontacts -u -n; then
-    echo "gcontacts failed, please run manually." |~/bin/pymail -r $(git config user.email|sed "s/.*@/$(hostname)@/") -s "gcontacts error" $(git config user.email)
+if ! ~/git/vmexam/google/contacts/backup -n; then
+    echo "backup failed, please run manually." |~/bin/pymail -r $(git config user.email|sed "s/.*@/$(hostname)@/") -s "google contacts backup error" $(git config user.email)
     exit
 fi
 
-xmllint --format ~/.gcontacts/contacts.xml > contacts.xml
+cp ~/.google-contacts/contacts.json .
 
-# Filter out some noise.
-sed -i 's/ ns1:etag="[^"]\+"//' contacts.xml
-sed -i '/:updated>/d' contacts.xml
-sed -i '/:edited>/d' contacts.xml
-
-git add contacts.xml && git commit -m "$(date +%Y-%m-%d)"
+git add contacts.json && git commit -m "$(date +%Y-%m-%d)"
 
 # vim:set shiftwidth=4 softtabstop=4 expandtab:
