mirror, rsync: partially restore genesis backup

diff --git a/mirror/rsync b/mirror/rsync
--- a/mirror/rsync
+++ b/mirror/rsync
@@ -49,6 +49,13 @@ wilson)
         exit 1
     fi
     ;;
+genesis)
+    cd genesis
+    if ! rsync -avP --delete-after -x genesis.vmiklos.hu:/etc/teleirc/ .; then
+        echo "rsync failed giving up"
+        exit 1
+    fi
+    ;;
 *)
     echo "error: missing machine"
     echo "state of backups:"
