thermodump: fix error handling now that i actually tested it

diff --git a/bash/thermodump b/bash/thermodump
--- a/bash/thermodump
+++ b/bash/thermodump
@@ -24,14 +24,16 @@ if [ ! -e "${csv}" ]; then
     echo "date-time,temperature,humidity" > ${csv}
 fi
 
-data=$(curl -s -f http://192.168.0.118/temp 2>&1)
-if [ $? != 0 ]; then
+data="$(curl -s -f http://192.168.0.118/temp 2>&1)"
+ret=$?
+if [ ${ret} != 0 ]; then
     today="$(date +%Y%m%d)"
     # Send email only once a day.
     if ! grep -q "${today}" errors.log; then
-        echo "${data}" |~/bin/pymail -r "$(git config user.email|sed "s/.*@/$(hostname)@/")" -s "thermodump error for ${today}" $(git config user.email)
+        echo "Error code ${ret}" |~/bin/pymail -r "$(git config user.email|sed "s/.*@/$(hostname)@/")" -s "thermodump error for ${today}" $(git config user.email)
         echo "${today}" >> errors.log
     fi
+    exit
 fi
 
 # Strip 'NA,' prefix.
